require 'spec_helper'
require 'rspec/snapshot'
require 'rspec/collection_matchers'
require 'rspec/expectations'
require_relative '../lib/nexmo_markdown_renderer'
require_relative '../lib/nexmo_markdown_renderer/initializers/doc_finder'
